apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.4
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-password
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-user-creds
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-user-creds
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mariadb-config
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: mariadb-config
        configMap:
          name: mariadb-config