apiVersion: v1
kind: Secret
metadata:
  name: mariadb-root-password
type: Opaque
data:
  password: S3ViZXJuZXRlc1JvY2tzIQ==  # Base64 encoded "KubernetesRocks!"
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-user-creds
type: Opaque
data:
  MYSQL_USER: a3ViZXVzZXI=  # Base64 encoded "kubeuser"
  MYSQL_PASSWORD: a3ViZS1zdGlsbC1yb2Nrcw==  # Base64 encoded "kube-still-rocks"